person:
  age: 18
  user-name: 黎明
  birth: 2020/9/22 21:52:56
  boss: false
  pet:
      name: tomcat
      weight: 23.4
  interests: [篮球,足球]
  animal:
    - jerry
    - lili
  score:
    english:
    first: 30
    second: 40
    third: 50
    math: [ 131,140,148 ]
    chinese: { first: 128,second: 136 }
  salarys: [3999,4999.98,5999.99]
  all-pets:
    sick:
      - {name: 阿狗,weight: 99.99}
      - name: 阿毛
        weight: 88088
      - name: 阿虫
        weight: 66.66
    health:
      - {name: 阿华,weight: 1999}