spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#    contentnegotiation:
#      favor-parameter: true
    #静态资源访问前缀
#    mvc:
#    static-path-pattern: /res/**
  #改变默认的静态资源路径/static /public/resources/META-INF/resources失效
#  web:
#    resources:
#      static-locations:
#        [ classpath:/haha/]
#    add-mappings: true
#    cache:
#      period: 11000
#server:
#  servlet:
#    context-path: /world

